try to elevate privileges with run0
This required systemd >= 256, which is the first version to
ship with run0...

https://www.freedesktop.org/software/systemd/man/run0.html

diff --git a/bin/pacman-offline b/bin/pacman-offline
--- a/bin/pacman-offline
+++ b/bin/pacman-offline
@@ -34,6 +34,11 @@ while getopts 'cfhrty' opt; do
 done
 
 if [ "${UID}" -ne 0 ]; then
+	if command -v run0 >/dev/null; then
+		echo 'Missing privileges, trying to elevate.' >&2
+		exec run0 "${0}" "${@}"
+	fi
+
 	echo "You need elevated privileges. Please run as user 'root'!" >&2
 	exit 1
 fi
